package behindthenumbers.model;


public class County {
	protected int CountyID;
	protected int CountyFips;
	protected String CountyName;
	protected int StateID;

	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public County(int CountyID, int CountyFips, String CountyName, int StateID) {
		this.CountyID = CountyID;
		this.CountyFips = CountyFips;
		this.CountyName = CountyName;
		this.StateID = StateID;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public County(int CountyID) {
		this.CountyID = CountyID;
	}
	
	public County(String CountyName) {
		this.CountyName = CountyName;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.

	public County(int CountyFips, String CountyName, int StateID) {
		this.CountyFips = CountyFips;
		this.CountyName = CountyName;
		this.StateID = StateID;
	}

	public int getCountyId() {
		return CountyID;
	}

	public void setCountyId(int CountyID) {
		this.CountyID = CountyID;
	}

	public int getCountyFips() {
		return CountyFips;
	}

	public void setCountyFips(int CountyFips) {
		this.CountyFips = CountyFips;
	}

	public String getCountyName() {
		return CountyName;
	}

	public void setCountyName(String CountyName) {
		this.CountyName = CountyName;
	}

	public int getStateID() {
		return StateID;
	}

	public void setStateID(int StateID) {
		this.StateID = StateID;
	}

}