package behindthenumbers.model;


public class State {
	protected int StateID;
	protected String StateName;
	protected String StateAbbreviation;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public State(int StateID, String StateName, String StateAbbreviation) {
		this.StateID = StateID;
		this.StateName = StateName;
		this.StateAbbreviation = StateAbbreviation;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public State(int StateID) {
		this.StateID = StateID;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.

	public State(String StateName, String StateAbbreviation) {
		this.StateName = StateName;
		this.StateAbbreviation = StateAbbreviation;
	}

	public int getStateId() {
		return StateID;
	}

	public void setStateId(int StateID) {
		this.StateID = StateID;
	}

	public String getStateName() {
		return StateName;
	}

	public void setStateName(String StateName) {
		this.StateName = StateName;
	}

	public String getStateAbbreviation() {
		return StateAbbreviation;
	}

	public void setStateAbbreviation(String StateAbbreviation) {
		this.StateAbbreviation = StateAbbreviation;
	}
}